sudo: required

language: node_js

node_js:
  - "10.15.3"
services:
  - docker

cache:
  yarn: true

branches:
  only:
    - master
    
notifications:
  slack: hora-da-hora:nrnWEevu7LsNkubXbVAgfdVR

script:
  - docker build -t frontend .

deploy:
  - provider: script
    script: bash scripts/deploy_image.sh
    on:
      branch: master


addons:
  apt:
    packages:
      - docker-ce

