sudo: required

language: node_js

node_js:
  - "10.15.3"

services:
  - docker

notifications:
  slack: hora-da-hora:0nFQxr2PykmKhNkJ78xYJMOP

stages:
  - name: deploy docker image
    if: branch = configurar-ambiente

jobs:
  include:
    - stage: deploy docker image
      script: 
        - bash scripts/deploy_image.sh

addons:
  apt:
    packages:
      - docker-ce

