sudo: required

language: node_js

node_js:
  - "10.15.3"

services:
  - docker

stages:
  - Build image
  - Build docker image

notifications:
  slack: hora-da-hora:0nFQxr2PykmKhNkJ78xYJMOP

before_script:
  - docker build -t maismonitoria/frontend .

jobs:
  include:
    - stage: "Build image"
      name: "Construindo image"
      script:
        - docker run maismonitoria/frontend yarn build 
#    - stage: "Build docker image"
#      name: "Publicando image"
#      if: branch = develop
#      script: 
#        - bash scripts/deploy_image.sh
      
addons:
  apt:
    packages:
      - docker-ce
