sudo: required

language: node_js

node_js:
  - "10.15.3"
services:
  - docker

cache:
  yarn: true
    
notifications:
  slack: hora-da-hora:0nFQxr2PykmKhNkJ78xYJMOP

script:
  - docker build -t frontend .

deploy:
  - provider: script
    script: bash scripts/deploy_image.sh

addons:
  apt:
    packages:
      - docker-ce

