sudo: required

language: node_js

node_js:
  - "10.15.3"

services:
  - docker

stages:
#  - Unit test
  - Build docker image

notifications:
  slack: hora-da-hora:0nFQxr2PykmKhNkJ78xYJMOP

jobs:
  include:
    - stage: "Build docker image"
      name: "Build docker image"
      script:
        - bash ./scripts/deploy_homolog.sh
        
#deploy:
#    - provider: script
#      skip_cleanup: true
#      script: bash ./scripts/deploy_prod.sh
#      on:
#        branch: master
#    - provider: script
#      skip_cleanup: true
#      script: bash ./scripts/deploy_homolog.sh
      
addons:
  apt:
    packages:
      - docker-ce
