sudo: required

language: node_js

node_js:
  - "10.15.3"

services:
  - docker

stages:
  - Unit test
  - Build docker image

notifications:
  slack: hora-da-hora:0nFQxr2PykmKhNkJ78xYJMOP

before_script:
  - docker build -t maismonitoria/frontend .

jobs:
  include:
    - stage: "Unit test"
      name: "Unit test"
      script:
        - yarn run test -u --coverage
        - ./node_modules/.bin/codecov -t ${CODECOV_TOKEN}
#    - stage: "Build docker image"
#      name: "Publicando image"
#      if: branch = develop
#      script: 
#        - bash scripts/deploy_image.sh
      
addons:
  apt:
    packages:
      - docker-ce
