sudo: required

language: node_js

node_js:
  - "10.15.3"

services:
  - docker

branches:
  - configurar-ambiente
cache:
  yarn: true
    
notifications:
  slack: hora-da-hora:0nFQxr2PykmKhNkJ78xYJMOP

script:
  - docker build -t frontend .

deploy:
  - provider: script
    script: bash scripts/deploy_image.sh
    on:
      branch: configurar-ambiente

addons:
  apt:
    packages:
      - docker-ce

