sudo: required

language: 
  - node_js
  - python

node_js:
  - "10.15.3"
python:
  - "3.6"

services:
  - docker

stages:
  - Unit test
  - Build docker image homolog
  - Build docker image production
  - Upgrade service
  
notifications:
  slack: hora-da-hora:0nFQxr2PykmKhNkJ78xYJMOP

before_install:
  - pip install requests

jobs:
  include:
    - stage: "Unit test"
      name: "Unit test"
      script:
        - yarn run test -u --coverage
        - ./node_modules/.bin/codecov -t ${CODECOV_TOKEN}
    - stage: "Deploy image homolog"
      if: branch = develop
      script: bash ./scripts/deploy_homolog.sh
    - stage: "Deploy image prodution"
      if: branch = master
      script: bash ./scripts/deploy_prod.sh
    - stage: "Upgrade service"
      if: branch = develop
      script: python ./scripts/upgrade.py
      
addons:
  apt:
    packages:
      - docker-ce
