sudo: required

language: node_js

node_js:
  - "10.15.3"

services:
  - docker

notifications:
  slack: hora-da-hora:0nFQxr2PykmKhNkJ78xYJMOP

before_script:
  - docker build -t maismonitoria/frontend .
  - docker run maismonitoria/frontend yarn build 

stages:
  - name: deploy docker image
  
jobs:
  include:
    - stage: deploy docker image
      script: 
        - bash scripts/deploy_image.sh
      on:
        branch: master
addons:
  apt:
    packages:
      - docker-ce

