
before_script:
  - docker build -t maismonitoria/frontend .

jobs:
  include:
    - stage: "Build image"
      name: "Construindo image"
      script:
        - docker run maismonitoria/frontend yarn build 
#    - stage: "Build docker image"
#      name: "Publicando image"
#      if: branch = develop
#      script: 
#        - bash scripts/deploy_image.sh
      
sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.22.0

stages:
stages:
  - Build image
  - Build docker image
  
#notifications:
#  slack: hora-da-hora:0nFQxr2PykmKhNkJ78xYJMOP

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

jobs:
  include:
    - stage: "Unit test"
      name: "Unit test"
      script:
        - make build
        - docker network create api-backend
        - make run-d
        - make test-coverage
        - docker-compose exec frontend codecov -t ${CODECOV_TOKEN}
        
after_success:
  - docker-compose down