sudo: required

language: 
  - node_js
  - python

node_js:
  - "10.15.3"
python:
  - "3.6"

services:
  - docker

stages:
  - Unit test
  - Build docker image

notifications:
  slack: hora-da-hora:0nFQxr2PykmKhNkJ78xYJMOP

before_install:
  - pip install requests

jobs:
  include:
    - stage: "Unit test"
      name: "Unit test"
      script:
        - yarn run test -u --coverage
        - ./node_modules/.bin/codecov -t ${CODECOV_TOKEN}

deploy:
    - provider: script
      skip_cleanup: true
      script: bash ./scripts/deploy_prod.sh
      on:
        branch: master
    - provider: script
      skip_cleanup: true
      script: bash ./scripts/deploy_homolog.sh
      script: python ./scripts/upgrade.py
      on:
        branch: develop

addons:
  apt:
    packages:
      - docker-ce
