sudo: required

language: node_js

node_js:
  - "10.15.3"

services:
  - docker

branches:
  - configuracao-ambiente
cache:
  yarn: true

stages:
  - name: deploy docker image
    
jobs:
  include:
    - stage: deploy docker image
      script: 
        - bash scripts/deploy_image.sh
      on:
        branch: configuracao-ambiente
addons:
  apt:
    packages:
      - docker-ce

