version: "3"
services:
  frontend:
    container_name: "frontend"
    build: ./
    ports:
      - "3000:3000"
    command: bash -c "bash"
    volumes:
      - ./:/app
    environment:
      - REACT_APP_PATH_KEY=${REACT_APP_PATH_KEY}
      - REACT_APP_AUTH=${REACT_APP_AUTH}
      - REACT_APP_GATEWAY=${REACT_APP_GATEWAY}
      - URL_SERVICE_MONITORIA=${URL_SERVICE_MONITORIA}
    networks:
      - api-backend
    tty: true  

networks:
  api-backend:
    external:
      name: api-backend