version: "3"
services:
  frontend:
    container_name: "frontend"
    build: ./
    command: bash -c "yarn start"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    tty: true  
    networks:
      - api-backend
      
networks:
  api-backend:
    external:
      name: api-backend  