version: "3"
services:
  frontend:
    container_name: "frontend"
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    networks:
      - api-backend

networks:
  api-backend:
    external:
      name: api-backend  