version: "3"
services:
  frontend:
    container_name: "frontend"
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    environment:
      - REACT_APP_PATH_KEY=${REACT_APP_PATH_KEY}
      - REACT_APP_AUTH=${REACT_APP_AUTH}
    networks:
      - api-backend

networks:
  api-backend:
    external:
      name: api-backend